### ISSUE TITLE
iOS app store rejection due to HKClinicalRecord

### ISSUE THREAD

**Issue by vgupta16** [EddyVerbruggen/HealthKit#103]
The Apple app store is rejecting applications that use this plugin without using the features of the Clinical Health Records API. Even though our app is explicitly not granting Clinical Health API access, Apple is rejecting based on this string - "HKClinicalRecord" being present

**Comment by EddyVerbruggen** [comment]
@vgupta16 That was addede in https://github.com/EddyVerbruggen/HealthKit/pull/100 - perhaps stick to version 0.5.5 to avoid the problem.

Not sure what to do beyond that..

**Comment by EddyVerbruggen** [comment]
Yeah and that should, in turn, trigger a hook that copies in the file containing `HKClinicalRecord`, otherwise, it'll still be part of the bundle. But I can't give that any priority, unfortunately.

**Comment by rossmartin** [comment]
@vgupta16 Do you have the `Privacy - Health Records Usage Description` (`NSHealthClinicalHealthRecordsShareUsageDescription`) in your app's `info.plist`?  I could see them rejecting the app if you don't have this in your `info.plist`. 

I'm starting work on adding two new functions to the plugin for reading clinical data.  I'll see what I can do about this issue.  I don't think that any special handling needs to be done on whether to include a file containing `HKClinicalRecord`.  My PR didn't add any new header/source files.  If your app uses HealthKit there is an additional capability you'll need to check for access to the clinical data - 

![image](https://user-images.githubusercontent.com/2498502/48959402-b2122a80-ef2a-11e8-994f-00ebe481070e.png)

I wonder if they reject the app because there are references to the `HKClinicalRecord` in the code but that checkbox is not checked and the `NSHealthClinicalHealthRecordsShareUsageDescription` is missing from the `info.plist`.  The plugin install does not automatically check the `Health Records` checkbox.

**Comment by rossmartin** [comment]
@vgupta16 I have this issue solved in my fork (as well as other improvements for the clinical types, refactoring, and removal of deprecated APIs).  I have separated the the implementation of accessing clinical records from the non clinical types.  This will make rejection due to `HKClinicalRecord` no longer an issue.  And for those that want to use `HKClinicalRecord` they can if they want.  

I'll be updating the docs and example and then submitting a PR to solve this issue soon.

**Comment by vgupta16** [comment]
@rossmartin Great! Thank you for the update and I look forward to testing it out in our application.
